{"version":1,"resource":"vscode-remote://wsl%2Bubuntu/home/soufian/holbertonschool-higher_level_programming/python-exceptions/1-safe_print_integer.py","entries":[{"id":"r5LI.py","timestamp":1717426092988},{"id":"J7lC.py","timestamp":1717426509168},{"id":"M0qy.py","timestamp":1717426553398},{"id":"QKbA.py","timestamp":1717426563988},{"id":"v7JZ.py","timestamp":1717426579698},{"id":"M7iG.py","source":"undoRedo.source","timestamp":1717426726338},{"id":"DoL7.py","timestamp":1717426746718},{"id":"q2ja.py","timestamp":1717426764408},{"id":"mvXy.py","timestamp":1717426788708},{"id":"eup3.py","timestamp":1717426853978},{"id":"Q3F0.py","timestamp":1717426900168},{"id":"8rfv.py","source":"undoRedo.source","timestamp":1717426934018},{"id":"K4Lb.py","timestamp":1717426987618},{"id":"iqKo.py","timestamp":1717427030668},{"id":"T3SD.py","timestamp":1717427088358},{"id":"I8pj.py","timestamp":1717427133108},{"id":"i4wN.py","timestamp":1717427149798},{"id":"teH4.py","timestamp":1727109749946},{"id":"rqaI.py","timestamp":1727891758966},{"id":"MUNh.py","timestamp":1738618765234}]}